var PublicLists={MAX_NUMBER_OF_LISTS:3,MAX_NUMBER_OF_TRANSLATIONS:7,_buildPublicListsUrl:function(a,b,e,c){if("undefined"!==typeof PUBLIC_LISTS_URL)return a=PUBLIC_LISTS_URL+"?languagePairs\x3d"+a+"\x26length\x3d"+("number"===typeof e?e:PublicLists.MAX_NUMBER_OF_LISTS)+"\x26filterByFavouriteText\x3d"+encodeURIComponent(b),"number"===typeof c&&0<c&&(a+="\x26nbTranslations\x3d"+c),a},_buildListTermsHtml:function(a){var b="";if(a.favourites&&0<a.favourites.length){for(var e=(request.srctext||"").toLowerCase(),
c=[],d=0;d<a.favourites.length&&7>c.length;d++)a.favourites[d].srcText.toLowerCase()!==e&&c.push(a.favourites[d]);b+="\x3cdiv class\x3d'list-preview-items'\x3e";termsToAdd=[];for(a=0;a<c.length;a++)termsToAdd.push(encodeHTMLEntities(c[a].srcText||""));b+=termsToAdd.join(", ")+"...\x3c/div\x3e"}return b},_buildListCardHtml:function(a){var b="\x3ca class\x3d'vocabulary-list-item' data-id\x3d'"+a.id+"' href\x3d'"+urls.vocabulary_url+"/"+a.id+"'\x3e",b=b+"\x3cdiv class\x3d'list-header'\x3e";a.emoji&&
(b+="\x3cspan class\x3d'list-emoji'\x3e\x3cimg width\x3d'24' height\x3d'24' src\x3d'"+emojisURL.replace("{0}",a.emoji)+"'/\x3e\x3c/span\x3e");b+="\x3cspan class\x3d'list-name'\x3e"+encodeHTMLEntities(a.listName||"")+"\x3c/span\x3e";b+="\x3c/div\x3e";if(a.description)var e=encodeHTMLEntities(a.description),b=b+("\x3cp class\x3d'list-description' title\x3d'"+e.replace(/'/g,"\x26#39;")+"'\x3e"+e+"\x3c/p\x3e");b=b+"\x3cdiv class\x3d'list-content'\x3e"+PublicLists._buildListTermsHtml(a);b+="\x3cdiv class\x3d'vocabulary-cta-container'\x3e\x3cspan class\x3d'icon go-right' title\x3d'"+
constants.strings.results_vocabulary_lists_cta.replace(/'/g,"\x26#39;")+" - ";b+=constants.strings.results_vocabulary_lists_terms.replace("%1$s",a.numFavourites)+"'\x3e\x3c/span\x3e";return b+"\x3c/div\x3e\x3c/div\x3e\x3c/a\x3e"},_buildTopChipHtml:function(a){var b=PublicLists._buildListTermsHtml(a),b="\x3ca class\x3d'vocabulary-topic-chip' title\x3d'"+(constants.strings.results_vocabulary_lists_tooltip.replace("%1$s",encodeHTMLEntities(request.srctext))+"\x3cbr\x3e"+b).replace(/'/g,"\x26#39;")+"' data-id\x3d'"+
a.id+"' href\x3d'"+urls.vocabulary_url+"/"+a.id+"'\x3e";a.emoji&&(b+="\x3cspan class\x3d'chip-cover'\x3e\x3cimg width\x3d'28' height\x3d'28' src\x3d'"+emojisURL.replace("{0}",a.emoji)+"'/\x3e\x3c/span\x3e");b+="\x3cspan class\x3d'chip-label'\x3e"+encodeHTMLEntities(a.listName||"")+"\x3c/span\x3e";return b+"\x3c/a\x3e"},searchVocabularyLists:function(){if(request.srctext&&request.srclang&&request.trglang){var a=PublicLists._buildPublicListsUrl(request.srclang+"-"+request.trglang,request.srctext,PublicLists.MAX_NUMBER_OF_LISTS,
PublicLists.MAX_NUMBER_OF_TRANSLATIONS);void 0!==a&&$.ajax({url:a,type:"get",dataType:"json",success:function(a){if(a&&a.results&&0<a.results.length){for(var b=constants.strings.results_vocabulary_lists_title.replace("%1$s","\x3cstrong\x3e"+encodeHTMLEntities(request.srctext)+"\x3c/strong\x3e"),c=Math.min(a.results.length,PublicLists.MAX_NUMBER_OF_LISTS),d='\x3csection id\x3d"vocabulary-lists-top-section"\x3e\x3cdiv id\x3d"vocabulary-lists-top-inner"\x3e\x3cspan class\x3d"vocabulary-lists-top-label"\x3e'+
constants.strings.results_vocabulary_lists_related+'\x3c/span\x3e\x3cdiv id\x3d"vocabulary-lists-top-slider"\x3e\x3cdiv id\x3d"vocabulary-lists-top-container"\x3e',b='\x3csection id\x3d"vocabulary-lists-related"\x3e\x3cdiv id\x3d"vocabulary-lists-related-container"\x3e\x3ch2\x3e'+b+'\x3c/h2\x3e\x3cdiv id\x3d"vocabulary-lists-related-wrapper"\x3e\x3cdiv id\x3d"vocabulary-lists-related-results"\x3e',f=0;f<c;f++)var g=a.results[f],d=d+PublicLists._buildTopChipHtml(g),b=b+PublicLists._buildListCardHtml(g);
d+="\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/section\x3e";b+="\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/section\x3e";exists(".rudeness-messages")?$(d).insertBefore(".rudeness-messages"):$(d).insertBefore("#examples-content");exists("#examples-bottom .buttons-after-examples")?$("#examples-bottom .buttons-after-examples").after(b):$("#examples-bottom .loading-pannel").after(b);createSliderElement("vocabulary-lists-related-results","vocabulary-lists-related-wrapper");createSliderElement("vocabulary-lists-top-container",
"vocabulary-lists-top-slider");$(window).resize(function(){createSliderElement("vocabulary-lists-related-results","vocabulary-lists-related-wrapper");createSliderElement("vocabulary-lists-top-container","vocabulary-lists-top-slider")});PublicLists._addGAEvents();buildTooltips()}},error:function(){}})}},_addGAEvents:function(){try{var a=Object.assign({event:"context_vocabulary",event_name:"vocabulary_display_lists_search",direction:request.srclang+"-"+request.trglang},getRequiredGAEventGeneralInfo(request.srctext));
sendGTMEvent(a)}catch(b){}$(document).on("click","#vocabulary-lists-top-section .vocabulary-topic-chip",function(){try{var a=Object.assign({event:"context_vocabulary",event_name:"vocabulary_click_go_to_list",direction:request.srclang+"-"+request.trglang,medium_id:"top-lists",variant_id:$(this).data("id")},getRequiredGAEventGeneralInfo(request.srctext));sendGTMEvent(a)}catch(e){}});$(document).on("click","#vocabulary-lists-related .vocabulary-list-item",function(){try{var a=Object.assign({event:"context_vocabulary",
event_name:"vocabulary_click_go_to_list",direction:request.srclang+"-"+request.trglang,medium_id:"bottom-lists",variant_id:$(this).data("id")},getRequiredGAEventGeneralInfo(request.srctext));sendGTMEvent(a)}catch(e){}})}};