var PublicLists={MAX_NUMBER_OF_LISTS:3,MAX_NUMBER_OF_TRANSLATIONS:7,data:{},_buildPublicListsUrl:function(b,a,d,e,c){if("undefined"!==typeof PUBLIC_LISTS_URL){b=PUBLIC_LISTS_URL+"?languagePairs\x3d"+b+"\x26length\x3d"+("number"===typeof d?d:PublicLists.MAX_NUMBER_OF_LISTS)+"\x26filterByFavouriteText\x3d"+encodeURIComponent(a);if(!c&&"undefined"!==typeof request&&request.dymBaseforms&&request.dymBaseforms.length)for(c=0;c<request.dymBaseforms.length;c++)b+="\x26alternativeFilterByFavouriteText\x3d"+
encodeURIComponent(request.dymBaseforms[c]);"number"===typeof e&&0<e&&(b+="\x26nbTranslations\x3d"+e);return b}},_buildListTermsHtml:function(b){var a="";if(b.favourites&&0<b.favourites.length){for(var d=(PublicLists.data.text||"").toLowerCase(),e=[],c=0;c<b.favourites.length&&7>e.length;c++)b.favourites[c].srcText.toLowerCase()!==d&&e.push(b.favourites[c]);a+="\x3cdiv class\x3d'list-preview-items'\x3e";termsToAdd=[];for(b=0;b<e.length;b++)termsToAdd.push(encodeHTMLEntities(e[b].srcText||""));a+=
termsToAdd.join(", ")+"...\x3c/div\x3e"}return a},_buildListCardHtml:function(b){var a="\x3ca class\x3d'vocabulary-list-item' data-id\x3d'"+b.id+"' href\x3d'"+urls.vocabulary_url+"/"+b.id+"'\x3e",a=a+"\x3cdiv class\x3d'list-header'\x3e";b.emoji&&(a+="\x3cspan class\x3d'list-emoji'\x3e\x3cimg width\x3d'44' height\x3d'44' src\x3d'"+emojisURL.replace("{0}","big-lm").replace("{1}",b.emoji)+"' onerror\x3d\"this.onerror\x3dnull;this.src\x3d'"+emojisURL.replace("{0}","mini-lm").replace("{1}","U+1F517")+
"';\"/\x3e\x3c/span\x3e");a+="\x3cspan class\x3d'list-name'\x3e"+encodeHTMLEntities(b.listName||"")+"\x3c/span\x3e";a+="\x3c/div\x3e";if(b.description)var d=encodeHTMLEntities(b.description),a=a+("\x3cp class\x3d'list-description' title\x3d'"+d.replace(/'/g,"\x26#39;")+"'\x3e"+d+"\x3c/p\x3e");a=a+"\x3cdiv class\x3d'list-content'\x3e"+PublicLists._buildListTermsHtml(b);a+="\x3cdiv class\x3d'vocabulary-cta-container'\x3e\x3cspan class\x3d'icon go-right' title\x3d'"+constants.strings.results_vocabulary_lists_cta.replace(/'/g,
"\x26#39;")+" - ";a+=constants.strings.results_vocabulary_lists_terms.replace("%1$s",b.numFavourites)+"'\x3e\x3c/span\x3e";return a+"\x3c/div\x3e\x3c/div\x3e\x3c/a\x3e"},_buildTopChipHtml:function(b){var a=PublicLists._buildListTermsHtml(b),a="\x3ca class\x3d'vocabulary-topic-chip' title\x3d'"+(constants.strings.results_vocabulary_lists_tooltip.replace("%1$s",encodeHTMLEntities(PublicLists.data.text))+"\x3cbr\x3e"+a).replace(/'/g,"\x26#39;")+"' data-id\x3d'"+b.id+"' href\x3d'"+urls.vocabulary_url+
"/"+b.id+"'\x3e";b.emoji&&(a+="\x3cspan class\x3d'chip-cover'\x3e\x3cimg width\x3d'36' height\x3d'36' src\x3d'"+emojisURL.replace("{0}","big-lm").replace("{1}",b.emoji)+"' onerror\x3d\"this.onerror\x3dnull;this.src\x3d'"+emojisURL.replace("{0}","mini-lm").replace("{1}","U+1F517")+"';\"/\x3e\x3c/span\x3e");a+="\x3cspan class\x3d'chip-label'\x3e"+encodeHTMLEntities(b.listName||"")+"\x3c/span\x3e";return a+"\x3c/a\x3e"},searchVocabularyLists:function(){var b=PublicLists.data.text,a=PublicLists.data.sourceLang,
d=PublicLists.data.targetLang;b&&a&&d&&(a=PublicLists._buildPublicListsUrl(a+"-"+d,b,PublicLists.MAX_NUMBER_OF_LISTS,PublicLists.MAX_NUMBER_OF_TRANSLATIONS,PublicLists.data.reversed),void 0!==a&&$.ajax({url:a,type:"get",dataType:"json",success:function(a){if(a&&a.results&&0<a.results.length){for(var c=constants.strings.results_vocabulary_lists_title.replace("%1$s","\x3cstrong\x3e"+encodeHTMLEntities(b)+"\x3c/strong\x3e"),d=Math.min(a.results.length,PublicLists.MAX_NUMBER_OF_LISTS),e='\x3csection id\x3d"vocabulary-lists-top-section"\x3e\x3cdiv id\x3d"vocabulary-lists-top-inner"\x3e\x3cspan class\x3d"vocabulary-lists-top-label"\x3e'+
constants.strings.results_vocabulary_lists_related+'\x3c/span\x3e\x3cdiv id\x3d"vocabulary-lists-top-slider"\x3e\x3cdiv id\x3d"vocabulary-lists-top-container"\x3e',c='\x3csection id\x3d"vocabulary-lists-related"\x3e\x3cdiv id\x3d"vocabulary-lists-related-container"\x3e\x3ch2\x3e'+c+'\x3c/h2\x3e\x3cdiv id\x3d"vocabulary-lists-related-wrapper"\x3e\x3cdiv id\x3d"vocabulary-lists-related-results"\x3e',f=0;f<d;f++)var g=a.results[f],e=e+PublicLists._buildTopChipHtml(g),c=c+PublicLists._buildListCardHtml(g);
e+="\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/section\x3e";c+="\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/section\x3e";exists(".rudeness-messages")?$(e).insertBefore(".rudeness-messages"):$(e).insertBefore("#examples-content");$("#result-info").before(c);createSliderElement("vocabulary-lists-related-results","vocabulary-lists-related-wrapper");createSliderElement("vocabulary-lists-top-container","vocabulary-lists-top-slider");$(window).resize(function(){createSliderElement("vocabulary-lists-related-results",
"vocabulary-lists-related-wrapper");createSliderElement("vocabulary-lists-top-container","vocabulary-lists-top-slider")});PublicLists._addGAEvents();buildTooltips()}},error:function(){}}))},_addGAEvents:function(){try{var b=Object.assign({event:"context_vocabulary",event_name:"vocabulary_display_lists_search",direction:PublicLists.data.sourceLang+"-"+PublicLists.data.targetLang},getRequiredGAEventGeneralInfo(PublicLists.data.text));sendGTMEvent(b)}catch(a){}$(document).on("click","#vocabulary-lists-top-section .vocabulary-topic-chip",
function(){try{var a=Object.assign({event:"context_vocabulary",event_name:"vocabulary_click_go_to_list",direction:PublicLists.data.sourceLang+"-"+PublicLists.data.targetLang,medium_id:"top-lists",variant_id:$(this).data("id")},getRequiredGAEventGeneralInfo(PublicLists.data.text));sendGTMEvent(a)}catch(d){}});$(document).on("click","#vocabulary-lists-related .vocabulary-list-item",function(){try{var a=Object.assign({event:"context_vocabulary",event_name:"vocabulary_click_go_to_list",direction:PublicLists.data.sourceLang+
"-"+PublicLists.data.targetLang,medium_id:"bottom-lists",variant_id:$(this).data("id")},getRequiredGAEventGeneralInfo(PublicLists.data.text));sendGTMEvent(a)}catch(d){}})}};