function buildSynonymsRequest(a,b){$.ajax({url:urls.synonyms_host+(request.srclang+"/"+request.srctext+"?merge\x3dtrue\x26fuzzy\x3dfalse\x26rude\x3dtrue\x26examples\x3dfalse\x26maxPerPos\x3d8\x26maxPerCluster\x3d0\x26maxExpressions\x3d0"),headers:{"X-Reverso-Origin":"context.web"},type:"GET",contentType:"application/json",dataType:"json",success:function(b){a(b)},error:function(a){console.error(a);b(a)}})}
function escapeAttr(a){return null==a||""===a?"":String(a).replace(/&/g,"\x26amp;").replace(/"/g,"\x26quot;").replace(/</g,"\x26lt;")}
var DEFINITION_POS_STRINGS=Object.freeze({noun:"n.",verb:"v.",adjective:"adj.",adverb:"adv.",preposition:"prep.",conjunction:"conj.",pronoun:"pron.",interjection:"interj.",prefix:"pref.","combining form":"combform.",abbreviation:"abbr.",contraction:"contr.","adjective suffix":"adj-suf.",article:"art.","verb suffix":"v-suf.","noun suffix":"n-suf.",phrase:"ph.",unknown:"o.",determiner:"det.","auxiliary verb":"v-aux.",acronym:"acron.",expression:"exp.","phrasal verb":"ph-v.","verbal expression":"v-exp.",
other:"o."});function getEquivalentDefinitionPOS(a){return a?DEFINITION_POS_STRINGS[a.toLowerCase()]:""}function forEachClusterItem(a,b,k){if(a=a[b])if(Array.isArray(a))for(var c=0;c<a.length;c++)k(a[c],c);else for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&k(a[c],c)}
function buildBottomSynonymsSuggestions(a){if(a&&a.entries&&0!==a.entries.length)try{var b=function(b,c){var e=[],f;for(f in a.entries){var g=0,l=a.entries[f],h;for(h in l.clusters){if(g>=c)break;var d="",n=!0;forEachClusterItem(l.clusters[h],b,function(a){if(!(g>=c)){var b=a.word;b&&(g++,n||(d+='\x3cspan class\x3d"sug-separator"\x3e\x26nbsp;\x26#xB7;\x26nbsp;\x3c/span\x3e'),n=!1,d+="\x3ca href\x3d'"+k+toURL(b)+"' class\x3d'syn-link'\x3e",a&&a.register&&"rude"===a.register.toLowerCase()?d+="\x3cspan class\x3d'warn rude' title\x3d'"+
constants.strings.tooltip_rudeword+"'\x3e!\x3c/span\x3e ":a&&a.register&&"colloquial"===a.register.toLowerCase()&&(d+="\x3cspan class\x3d'warn colloquial' title\x3d'"+constants.strings.tooltip_colloquial+"'\x3e!\x3c/span\x3e "),d+=b+"\x3c/a\x3e")}});if(!n){var p="\x3cdiv class\x3d'pos-content'\x3e\x3cdiv class\x3d'pos-content-main'\x3e";if(l.pos&&!u){var q=getEquivalentDefinitionPOS(l.pos),m=constants.pos[q],r=q.toLowerCase().replace(/\s+/g,"-").replace(/[^a-z0-9-]/g,"");r||(r="pos-generic");m=m?
' title\x3d"'+escapeAttr(m)+'"':"";p+="\x3cdiv class\x3d'pos "+r+"'"+m+"\x3e"+escapeHtmlCharacterLessThan(q)+"\x26nbsp;\x3c/div\x3e"}p+="\x3c/div\x3e\x3c/div\x3e";e.push('\x3cspan class\x3d"syn-list"\x3e'+p+d+"\x3c/span\x3e");if(g>=c)break}}}return{rows:e,total:g}},k=context_path+"/"+getLocalizedPath()+"/"+getLocalizedPairURL(request.srclang,request.trglang)+"/",c={},e;for(e in a.entries)a.entries[e].pos&&(c[a.entries[e].pos.toLowerCase()]=!0);var u=1===Object.keys(c).length,h=b("synonyms",8),f=b("antonyms",
8);if(0===h.total&&0===f.total)$("#bottom-synonyms").remove();else{var v=$("#bottom-synonyms").attr("data-more-href")||"",w=escapeHtmlCharacterLessThan(constants.strings.results_synonyms_more),x='\x3cdiv class\x3d"more-synonyms-wrapper"\x3e\x3ca href\x3d"'+escapeAttr(v)+'" class\x3d"more-synonyms" rel\x3d"noopener"\x3e'+w+"\x3c/a\x3e\x3c/div\x3e",y='\x3cdiv class\x3d"synonyms-groups"\x3e'+h.rows.join("")+"\x3c/div\x3e"+x,z=constants.strings&&constants.strings.results_antonyms_title?constants.strings.results_antonyms_title:
"Antonyms",b="";f.rows.length&&(b='\x3cdiv class\x3d"synonyms-content antonyms-section"\x3e\x3ch3 class\x3d"bottom-antonyms-title"\x3e'+escapeHtmlCharacterLessThan(z)+"\x3c/h3\x3e"+f.rows.join("")+"\x3c/div\x3e");$("#bottom-synonyms .synonyms-content").html(y);$("#bottom-synonyms").append(b);buildTooltips()}}catch(t){console.error(t),$("#bottom-synonyms").remove()}else $("#bottom-synonyms").remove()}
function loadBottomSynonymsSuggestionsImpl(){exists("#bottom-synonyms")&&buildSynonymsRequest(function(a){buildBottomSynonymsSuggestions(a)},function(){$("#bottom-synonyms").addClass("hidden")})}$(document).on("click","#bottom-synonyms .more-synonyms",function(){try{sendGTMEvent(Object.assign({event:"context",event_name:"bottom_synonyms_showmore",direction:request.srclang+"-"+request.trglang,medium_id:"bottom-synonyms",medium_type:"link"},getRequiredGAEventGeneralInfo(request.srctext)))}catch(a){}});
var SynonymsLogic={buildSynonymsRequest:buildSynonymsRequest,loadBottomSynonymsSuggestions:loadBottomSynonymsSuggestionsImpl};